name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'e2e/**'
      - 'examples/**'
      - 'wiremock-graphql-extension/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - uses: getgauge/setup-gauge@master
        with:
          gauge-version: '1.6.9'
          gauge-plugins: java, html-report

      - name: Run unit test and install
        run: make install
        working-directory: e2e

      - name: Run docker for e2e
        run: make docker
        working-directory: e2e

      - name: Run e2e
        run: make clean test_compile run TAGS='!unimplemented'
        working-directory: e2e

      - name: Run remote e2e
        run: |-
          sed -i 's/baseUrl=http:\/\/localhost:8080/baseUrl=http:\/\/localhost:8888/' src/test/resources/config.properties
          make run TAGS='!unimplemented,remote'
        working-directory: e2e

  check-example-validity:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Install to local repository
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        working-directory: wiremock-graphql-extension

      - name: Check example validity kotlin
        run: mvn test
        working-directory: examples/testcontainers-kotlin

      - name: Check example validity java
        run: mvn test
        working-directory: examples/testcontainers-java
